### ISSUE TITLE
Guess wifi locations without GPS but other already scanned wifis around

### ISSUE THREAD

**Issue by Djfe** [mozilla/ichnaea#132]
Would it make sense to save wifi aps and cell towers without a GPS location or would that support spamming too much?

We could guess a rough location from nearby wifi aps and cell towers that have been scanned with a working GPS fix (and are in our database already).
We could save them and wait for future uploads that include nearby wifi aps and cell towers (we could wait x months for example before deleting them if it gets unlikely that another user will upload a GPS location for it, in the first months it is more likely as it could be a place where he/she is more often, after a few months it is more likely to be a place where he/she was on holiday).

This would need changes in mozstumbler and other  tools using our service as well.

It only makes sense to save/upload data if there are any nearby wifi aps/cell towers though and we need to double the radius in which the user could be in comparison to wifi aps/cell towers with a GPS location (->1000m instead of 500 (wifis) and 64km instead of 32 (cells)).

Or would the database grow way more rapidly if this get changed?

-> this is interesting for future search requests without a GPS location as well (integrated like Google's service into an OS) as this information can feed our database.

One problem though: we cannot guess if a wifi is moving or not.
Solution: this positional data will only be used if there are no other informations about the user's location (in the case of a search request).

Later on this data will be deleted if there is an accurate position for it (uploaded by a new submit).

We could save data about such entries showing how often it was used and delay a deletion if users are guessing their position from it (we want to keep it then) so that it will be more likely that one of them will be a stumbler (-> mostly for bigger cities).

**Comment by hannosch** [comment]
I actually ended up implementing this in the last weeks without realizing we had an issue about it :)

We use observations without GPS coordinates in two ways now:

- To validate that networks are still at the same place, if we get a matching observation. In the positive case we update a last_seen column to note when we last confirmed the networks position. In the negative case, we put the network on our blocklist as it has moved. The last_seen column is used at query time to influence our confidence score in each network. Networks we have seen more recently have a higher score than those we haven't seen in a long time.

- To create new records for networks we haven't seen before, but where we could figure out their position based on other networks in the same query. We update those "query" based networks based on consecutive sightings, which can also lead to them being blocked for moving around. Should we ever get a GPS-based reading for such a query based network, we simply replace our data based on the GPS data.

**Comment by Djfe** [comment]
lol ^^
nice, another issue bites the dust :) (and another one bites, and another one bites, ...)

I have a few questions, if you've got the time:
You use a different table for these networks, right?
An how do you take 5GHz networks into account, that a device might not be able to see (for blacklisting)
same goes for 5GHz ac wifi, UMTS/LTE/LTE Advanced etc.
or does it only take movements (to other places) into account (and not if a network is missing, that has been seen "here" before)

is there an issue on the client-side to get this implemented? (consecutive WiFi-/cell-scanning)
it might be harder to implement because of the rules regarding power saving
or atleast it might be worth to think about not disabling it as easily as GPS scanning (if it takes less power than GPS scanning)

passive wifi/cell scanning might not take much power at all, but is rewarding :)
especially since it could be included in Firefox (lib)

what do you mean by "replacing" do you give them that GPS coordinate with a very low accuracy
or are you trying to calculate a better accuracy for each of the network's points with bounding boxes or something smart like that?

Regards,
Djfe

**Comment by hannosch** [comment]
> You use a different table for these networks, right?

It's not a different table, but each of the networks has a "source" column, which currently can be either "gnss" (the umbrella term for GPS, Glonass, etcs.) or "query".

> An how do you take 5GHz networks into account, that a device might not be able to see (for blacklisting)
> same goes for 5GHz ac wifi, UMTS/LTE/LTE Advanced etc.
> or does it only take movements (to other places) into account (and not if a network is missing, that has been seen "here" before)

We currently don't take absence into account. The problem is that WiFi scans are fairly unreliable. On the same device, in the same place doing two consecutive WiFi scans often leads to two different sets of observed WiFi networks. Especially if there are a lot or some networks with weaker signals, you don't get them all each time you do a scan.

The other issue would be devices with only 2.4GHz / 5 GHz support or 802.11n or 802.11ac only networks which cannot be detected by all devices.

With those things in mind, "absence" is not a particularly trustworthy indicator and we currently ignore it.

> is there an issue on the client-side to get this implemented? (consecutive WiFi-/cell-scanning)

No. The client code is all driven by getting GPS signals, in the case of Firefox for Android even some other app initiating those GPS scans instead of the stumbler library itself. These days we get a sizable chunk of traffic from users querying the service without stumbling. Those are the users we get this data set from, like for example the microG UnifiedNlp backend or the geoclue library.

> what do you mean by "replacing" do you give them that GPS coordinate with a very low accuracy
> or are you trying to calculate a better accuracy for each of the network's points with bounding boxes or something smart like that?

Given a WiFi network for which we only have a query based position estimate so far. Should we get a GNSS based observation for it for the first time, we replace the information we have for this network based on the GNSS based data. We don't try to mix or merge those two. The problem here is that the accuracy / radius estimates of query based networks can be fairly large and since they are a derivative of our other data, not quite as trustworthy. It's not clear to me how exactly we should merge the data and get reasonable bounding boxes / radius estimates and what to do if the two are fairly far apart. For now I'm refusing to guess and simply replace the position / radius data.

**Comment by Djfe** [comment]
ok thx for your detailed answer :)

another idea:
What would/could happen if a query reveals two wifis but a gps scan in the same area reveals only one of them
should the other one's position be updated as well? (could be several other wifis)
if the other network has no other position but a list of nearby wifis, it could get one then
of course with a far bigger accuracy radius

what about MozStumbler queries? are those ignored because they will end up in the db later on anyways?


and what do you think about a half-active/passive stumbler only for cell/wifi
would that be useful?

maybe such a client could make a query every hour or so and if there are more than x wifi/cell networks around but the estimate from MLS has a bad accuracy it could keep on stumbling till the estimates get better again
(they should be better for a few minutes before it goes back to 1h stumbling)

yes this would wake the device, so maybe there should be a complete passive mode that you can choose or is activated when the battery level falls below y
this passive mode would only get the results of queries on interrupts, so that it doesn't poll at all
it should only save the results and work with them later on when the device is used again

just a concept that came to my mind
not sure how helpful this is.
Might increase the amount of networks MLS is able to reach

two last questions:
are query results excluded from the statistics so far?
what happened that made OpenCellID surpass MLS again? Did they merge with another db?

**Comment by hannosch** [comment]
> What would/could happen if a query reveals two wifis but a gps scan in the same area reveals only one of them
> should the other one's position be updated as well? (could be several other wifis)

As I said before, we don't trust "absence" of networks. There are too many reasons why we see networks only part of the time, most of them unrelated to whether or not the network is actually there.

> if the other network has no other position but a list of nearby wifis, it could get one then
> of course with a far bigger accuracy radius

Right, we thought about this idea of building up a graph of networks, where we only know which other networks they are close to, without knowing the position of any one of them. We think this provides too little extra value for the additional complexity it brings to the codebase. It would require us to get another graph database involved, to efficiently model and query these kinds of graphs at scale.

> what about MozStumbler queries? are those ignored because they will end up in the db later on anyways?

They aren't ignored, but they don't hurt. Typically we get the stumbling data first, and than the query data simply confirms that the networks are still at the same place. Even if it were the other way around, the potentially just query based networks would get replaced by the GNSS-based stumbling data afterwards.

> and what do you think about a half-active/passive stumbler only for cell/wifi
> would that be useful?

I'm not sure who the users are that would want this. We currently have two fairly clear modes, either passive stumbling or active stumbling. Either the stumbler is used in the background in an app like Firefox for Android, or you use it actively in the form of Mozilla Stumbler. In Firefox for Android, we specifically don't want users having to choose or configure the stumbler in any way. The UI there needs to remain a simple yes/no opt-in choice for users to actually feel comfortable to use it. And impact on data usage and battery similarly need to be as low as possible.

And once you run the stumbler app, you tend to be an enthusiast that is willing to part with some of their battery capacity to run the full active mode or will consciously stop and start the app.

> are query results excluded from the statistics so far?

No, they count into all the public stats we have. They account for about 5% of daily newly discovered unique networks, which is more than we expected, given that we still get much more data via stumbling than we do via queries.

> what happened that made OpenCellID surpass MLS again? Did they merge with another db?

Yes, they finally merged the MLS data into OpenCellID. So the OpenCellID number now shows the combined number of unique networks they get from both projects. In March it was 8 million in OCID, 21 million MLS, now we have 26 million in OCID and 23 million in MLS. Since they was a large overlap of about 5 million networks between the two datasets, the number of unique networks isn't the sum of the two numbers, but far less than that.

**Comment by hannosch** [comment]
> What would/could happen if a query reveals two wifis but a gps scan in the same area reveals only one of them
> should the other one's position be updated as well? (could be several other wifis)

As I said before, we don't trust "absence" of networks. There are too many reasons why we see networks only part of the time, most of them unrelated to whether or not the network is actually there.

> if the other network has no other position but a list of nearby wifis, it could get one then
> of course with a far bigger accuracy radius

Right, we thought about this idea of building up a graph of networks, where we only know which other networks they are close to, without knowing the position of any one of them. We think this provides too little extra value for the additional complexity it brings to the codebase. It would require us to get another graph database involved, to efficiently model and query these kinds of graphs at scale.

> what about MozStumbler queries? are those ignored because they will end up in the db later on anyways?

They aren't ignored, but they don't hurt. Typically we get the stumbling data first, and than the query data simply confirms that the networks are still at the same place. Even if it were the other way around, the potentially just query based networks would get replaced by the GNSS-based stumbling data afterwards.

> and what do you think about a half-active/passive stumbler only for cell/wifi
> would that be useful?

I'm not sure who the users are that would want this. We currently have two fairly clear modes, either passive stumbling or active stumbling. Either the stumbler is used in the background in an app like Firefox for Android, or you use it actively in the form of Mozilla Stumbler. In Firefox for Android, we specifically don't want users having to choose or configure the stumbler in any way. The UI there needs to remain a simple yes/no opt-in choice for users to actually feel comfortable to use it. And impact on data usage and battery similarly need to be as low as possible.

And once you run the stumbler app, you tend to be an enthusiast that is willing to part with some of their battery capacity to run the full active mode or will consciously stop and start the app.

> are query results excluded from the statistics so far?

No, they count into all the public stats we have. They account for about 5% of daily newly discovered unique networks, which is more than we expected, given that we still get much more data via stumbling than we do via queries.

> what happened that made OpenCellID surpass MLS again? Did they merge with another db?

Yes, they finally merged the MLS data into OpenCellID. So the OpenCellID number now shows the combined number of unique networks they get from both projects. In March it was 8 million in OCID, 21 million MLS, now we have 26 million in OCID and 23 million in MLS. Since they was a large overlap of about 5 million networks between the two datasets, the number of unique networks isn't the sum of the two numbers, but far less than that.
