### ISSUE TITLE
outdated library: mobile-codes causes ignoring some data

### ISSUE THREAD

**Issue by szjozsef** [mozilla/ichnaea#1421]
The mobile-codes library is marked unmaintained and is really out of date, is used internally to validate the data (at least during import).
The library code itself is ok, but the included json databases are out of date.
I managed to update the 2 relevant files, 
`
mobile-codes/mobile_codes/json/countries.json
mobile-codes/mobile_codes/json/mnc_operators.json
`
and mapped them into the container via :
`
-v "/host_folder/mnc_operators.json:/usr/local/lib/python3.8/site-packages/mobile_codes/json/mnc_operators.json" \
-v "/host_folder/countries.json:/usr/local/lib/python3.8/site-packages/mobile_codes/json/countries.json" \
`
Also the library's github repository do contain a parse.py script which should update this files, but that script is also out of date.
For the moment I published the updated files in a forked repository: `https://github.com/szjozsef/mobile-codes`
Maybe ichnaea should update internally this files from time to time (?), or at least document somewhere that if the files get outdated, data loss can occur.
I have updated the parse.py but because I have limited python knowledge only succeed to obtain the updated files with a combination of shell commands and the python script. If somebody with good python knowledge are willing to update the parse.py I can share my scripts with her/him.

**Comment by jwhitlock** [comment]
Thank you for your work on this problem, @szjozsef!

I see a couple of options to update this data:

1. Reach out to andymckay (an ex-Mozilla employee) and see if he is willing to transfer the project to Mozilla, so we can maintain it
2. Bring the code and data into this project, so we can maintain it

I searched for users of this library on GitHub:

https://github.com/search?q=path%3Arequirements+mobile-codes

The results were:

* This project
* https://github.com/mozilla/solitude - Archived. Solitude was the Payment Server for processing marketplace and addons payments.
* https://github.com/mozilla/webpay - Archived. Webpay is an implementation of the WebPaymentProvider spec. It hosts the payment flow inside ``navigator.mozPay()`` when making app purchases or in-app payments on Firefox OS.

I couldn't find any non-Mozilla projects or active projects that use this library. That makes me want to absorb the project into this one rather than keep it as an independent project.

I then looked at the forks:
* https://github.com/drstevens/mobile-codes - 1 change Nov 2015, switched the Wikipedia page, made some other script changes, regenerated output
* https://github.com/nToggle/mobile-codes - Same as drstevens
* https://github.com/impratikjaiswal/mobile-codes - No changes
* https://github.com/JaredLockhart-Mozilla/mobile-codes - No changes
* https://github.com/onlinecity/mobile-codes - No changes
* https://github.com/raymoondtang/mobile-codes - No changes
* https://github.com/szjozsef/mobile-codes - All your changes 😁 

After reviewing the forks, it seems there isn't a huge interest in this data, so (again) it seems to make more sense as part of the ichnaea project rather than a stand-alone library.

@szjozsef does it make sense to you to merge ``mobile-codes`` script and data into ichnaea, or do you have a reason it should be its own project?

I took a brief look at your updates. The difference between the two repositories looks larger than I'd expect:

https://github.com/andymckay/mobile-codes/compare/master...szjozsef:main

For ``countries.json`` it appears to be due to a change in sorting. For example, the entry for Armenia hasn't changed, but it appears it was previously sorted by two-letter code, and is now sorted by country name. I'd need to normalize the data to get a better feel for the change.

I'd be willing to look at your scripts as well. I suggest either checking them into your fork, or I use https://gist.github.com to share scripts.

**Comment by szjozsef** [comment]
Hello @jwhitlock ,
Indeed I changed the sorting, to be able to better compare the results between updates.
Also I uploaded the used scripts to update the data files:
`
https://github.com/szjozsef/mobile-codes/blob/main/download_data.sh
https://github.com/szjozsef/mobile-codes/blob/main/parse.py
`
parse.py is now a python3 script (originally was written for python2)
For sure, there is room for a lot of optimization in it.

Because the latest itu source file is still old (from 2018) maybe you can remove that part.
Also because the wikipedia pages should have all the data, maybe you can left out the mcc-mnc-table parsing
I included them to be on the safe side regarding data completeness.
Also I decided to "pretty" format the resulted json files from the shell script instead of the python script, just because I failed to obtain the same result as the original formatting of the json files :(
The data download part also should be possible to move into the python script, and maybe you can get rid completely of he shell script. 
Would be perfect if ichnaea could take care alone about updating the json files from time to time

**Comment by szjozsef** [comment]
The file in my fork:
- https://github.com/szjozsef/mobile-codes/blob/main/source_data/itu.json
It is extracted from the latest ITU document, also compared to the original itu.json, from andymckay, has the country information added, to make it a similar source as wikipedia.

**Comment by jwhitlock** [comment]
I'm going to start working on this issue tomorrow. The first step will be to import the data and code from https://github.com/andymckay/mobile-codes into the project instead of installing as a package. After that, we can start bringing in the new data and code.

I can either bring in your new code (I'll be listed as author, and mention you in the PR and comments), or you could open a PR once I've got things in place (you get listed as author, and we go through some rounds of code review). Do you have a preference on which way we proceed?

**Comment by szjozsef** [comment]
Please fell free to proceed as more convenient to you. I think is most easiest if you create the PR.
I'm happy my contribution is helping the project.

**Comment by szjozsef** [comment]
I moved to a different script the download part (creating a tmp folder and saving the data there)
https://github.com/szjozsef/mobile-codes/blob/main/data_download.py
Adapted the parser script to read the source files from the tmp folder instead of downloading them
https://github.com/szjozsef/mobile-codes/blob/main/parse.py

Regarding the country name changes, because the python-iso3166 library is used as country information source, the country names are based on the data from there, including the name change for USA an GB

As for the test data, it seems that the test cases needs some updates or a different approach, in 6 years a lot of thing changed in the mobile networks.
Let's see each cases:
- This should be ok even now:
```
    def test_mcc(self):
        countries = mobile_codes.mcc(u'302')
        self.assertEqual(len(countries), 1)
        self.assertEqual(countries[0].mcc, u'302')

```
- This test need some update:
```
    def test_mcc_multiple_codes(self):
        countries = mobile_codes.mcc(u'313')
        self.assertEqual(len(countries), 1)
        self.assertEqual(countries[0].mcc, [u'310', u'311', u'313', u'316'])

        # We even get multiple countries with multiple MCC each
        countries = mobile_codes.mcc(u'310')
        self.assertTrue(len(countries) > 1)
        for country in countries:
            self.assertTrue(len(country.mcc) > 1)
```
mcc - 313 is now used in USA and Puerto Rico , so it is not a good choice anymore for the first test, maybe 312 can be used there, then the line: self.assertEqual(countries[0].mcc, [u'310', u'311', u'313', u'316']) should be updated to: self.assertEqual(countries[0].mcc, [u'310', u'311', u'312', u'313', u'314', u'315', u'316'])
- The next tests should be ok, as is:
```
    def test_mcc_multiple_countries(self):
        countries = mobile_codes.mcc(u'505')
        self.assertEqual(len(countries), 2)

    def test_mcc_fail(self):
        countries = mobile_codes.mcc(u'000')
        self.assertEqual(len(countries), 0)

    def test_alpha2(self):
        country = mobile_codes.alpha2(u'CA')
        self.assertEqual(country.alpha2, u'CA')

    def test_alpha2_fail(self):
        self.assertRaises(KeyError, mobile_codes.alpha2, u'XX')

  def test_alpha3(self):
        country = mobile_codes.alpha3(u'CAN')
        self.assertEqual(country.alpha3, u'CAN')

    def test_alpha3_fail(self):
        self.assertRaises(KeyError, mobile_codes.alpha3, u'XYZ')

    def test_name(self):
        country = mobile_codes.name(u'canada')
        self.assertEqual(country.name, u'Canada')

    def test_numeric(self):
        country = mobile_codes.numeric(u'124')
        self.assertEqual(country.numeric, u'124')

    def test_numeric_fail(self):
        self.assertRaises(KeyError, mobile_codes.numeric, u'000')
```
- This consistency test also need some changes:
```
    def test_countries_match_mnc_operators(self):
        operators = mobile_codes._mnc_operators()
        operator_mccs = set([o.mcc for o in operators])
        # exclude test / worldwide mcc values
        operator_mccs -= set([u'001', u'901'])
        # exclude:
        # 312 - Northern Michigan University
        operator_mccs -= set([u'312'])

        countries = mobile_codes._countries()
        countries_mccs = []
        for country in countries:
            mcc = country.mcc
            if not mcc:
                continue
            elif isinstance(mcc, list):
                countries_mccs.extend(list(mcc))
            else:
                countries_mccs.append(mcc)

        countries_mccs = set(countries_mccs)

        # No country should have a mcc value, without an operator
        self.assertEqual(countries_mccs - operator_mccs, set())

        # No operator should have a mcc value, without a matching country
        self.assertEqual(operator_mccs - countries_mccs, set())
```
This exclusion should be extended:
```
        # exclude test / worldwide mcc values
        operator_mccs -= set([u'001', u'901'])
```
to:
```
        # exclude test / worldwide mcc values
        operator_mccs -= set([u'001', u'901', u'902', u'991', u'995', u'999'])
```
I thins the next exclusion can be eliminated:
```
        # exclude:
        # 312 - Northern Michigan University
        operator_mccs -= set([u'312'])
```
I did not know why that was required in the past...
- The next test case should work as expected, this is also an explanation for the null values in the countries.json:
```
class TestCountriesNoMCC(TestCase):

    def test_alpha2(self):
        country = mobile_codes.alpha2(u'AQ')
        self.assertEqual(country.mcc, None)

    def test_alpha3(self):
        country = mobile_codes.alpha3(u'ATA')
        self.assertEqual(country.mcc, None)

    def test_name(self):
        country = mobile_codes.name(u'antarctica')
        self.assertEqual(country.mcc, None)

    def test_numeric(self):
        country = mobile_codes.numeric(u'010')
        self.assertEqual(country.mcc, None)
```
- The next test case also need some change (for Puerto Rico):
```
class TestCountriesSpecialCases(TestCase):

    def test_puerto_rico(self):
        # Allow mainland US 310 as a valid code for Puerto Rico.
        # At least AT&T has cell networks with a mcc of 310 installed
        # in Puerto Rico, see
        # https://github.com/andymckay/mobile-codes/issues/10
        country = mobile_codes.alpha2(u'PR')
        self.assertEqual(country.mcc, [u'310', '330'])
```
this should be updated to:
```
class TestCountriesSpecialCases(TestCase):

    def test_puerto_rico(self):
        # Allow mainland US 310 as a valid code for Puerto Rico.
        # At least AT&T has cell networks with a mcc of 310 installed
        # in Puerto Rico, see
        # https://github.com/andymckay/mobile-codes/issues/10
        country = mobile_codes.alpha2(u'PR')
        self.assertEqual(country.mcc, [u'310', u'313', u'330'])
```
- the next test case should work as expected:
```
class TestMNCOperators(TestCase):

    def test_mcc(self):
        operators = mobile_codes.operators(u'302')
        mccs = set([o.mcc for o in operators])
        self.assertEqual(mccs, set([u'302']))

    def test_mcc_fail(self):
        operators = mobile_codes.operators(u'000')
        self.assertEqual(len(operators), 0)

    def test_mcc_mnc(self):
        operator = mobile_codes.mcc_mnc(u'722', '070')
        self.assertEqual(operator.mcc, u'722')
        self.assertEqual(operator.mnc, u'070')

    def test_mcc_mnc_fail(self):
        self.assertRaises(KeyError, mobile_codes.mcc_mnc, u'000', '001')
```
- About the last test case:
```
class TestSIDOperators(TestCase):

    def test_sid_operators(self):
        operators = mobile_codes.sid_operators(u'1')
        countries = set([operator.country for operator in operators])
        mccs = set()
        for operator in operators:
            mccs = mccs.union(set([mcc for mcc in operator.mcc]))
        self.assertEquals(countries, set(['United States']))
        self.assertEquals(mccs, set([u'313', u'311', u'310', u'316']))

    def test_sid_operators_fail(self):
        operators = mobile_codes.operators(u'000')
        self.assertEqual(len(operators), 0)
```
It is referring to the SID operators, that database I think is not used any more and was not updated by any means.

**Comment by jwhitlock** [comment]
Thanks @szjozsef, I'll update PR #1442 with this feedback.

**Comment by jwhitlock** [comment]
I've merged #1444 then #1442. I'm not sure if these will go to production in 2020 or early 2021.

**Comment by szjozsef** [comment]
Thank you for your effort to update that libraries. 
From now on (after will go to production) also the https://location.services.mozilla.com servers will accept the data from the new/changed networks (which was added/changed in the pat 6 years).
Maybe a periodic task should be configured to update the databases from time to time (at least once in a month or even once in a week) ?

**Comment by jwhitlock** [comment]
I agree. I've opened issue #1455 with the steps for manually updating the data.

**Comment by szjozsef** [comment]
If the pull request #1469 will get merged, then just one entry from the countries.json remain unsolved :
["Virgin Islands, U.S.", "VI", "VIR", "850", null]
The best way to solve that would be to create the correct table on the : https://en.wikipedia.org/wiki/Mobile_Network_Codes_in_ITU_region_3xx_(North_America) page, similar to the one for Guam, Northern Mariana Islands...

**Comment by jwhitlock** [comment]
The new code, including PR #1470, is now deployed to production at https://location.services.mozilla.com. Thanks, @szjozsef!
