### ISSUE TITLE
Importing issues with ichnaea/scripts/load_cell_data.py

### ISSUE THREAD

**Issue by szjozsef** [mozilla/ichnaea#1423]
When using the script: ichnaea/scripts/load_cell_data.py
I managed to use this script to import the "Full Cell Exports" and the "Differential Cell Exports" from Mozilla location service.
However when importing the same kind of data from a 3rd party provider a few issues occurred.
Application crash, instead of just ignoring the wrong data, when the input data contained any of the following values for: 

-  radio = 0
-  radio = CDMA
-  area = 0
-  area = 65534
-  area = 65535
-  cell = 0
-  cell >= 268435456

in the input csv with the headers:
`
radio,mcc,net,area,cell,unit,lon,lat,range,samples,changeable,created,updated,averageSignal
`
after filtering out this kind of data, the import worked well.

**Comment by jwhitlock** [comment]
The last time I tried a full import (see https://github.com/mozilla/ichnaea/pull/945#discussion_r334599506), it failed, so it is good to hear it succeeded for you.

I'm tempted to flesh out the options:

1. By default, log a warning about each line of failed data, return a non-zero exit code
2. ``--fail-on-data-error`` - Fail on the first data error, return a non-zero exit code
3. ``--dry-run`` - Validate but don't update the database
4. ``--failures-to=<filename>`` - Output failed rows to another CSV file

Logging warnings rather than failing the import would be ideal, and good enough for most people.

As interesting as this is, I don't think it is critical for Ichnaea to import 3rd party data, so I don't think it will make it to my do-it-soon bug list.
