### ISSUE TITLE
Add signal strength based location with maximum signal level

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#302]
Is it possible to calculate (in example GSM ) the range from a cellid where the signal strength is -51 dBm or ASU=31 and use this calculated value if i are in this range?
When i near the base station i get the maximal signal level and are in the calculated range.

**Comment by hannosch** [comment]
We have addressed the main idea here recently via ae6db2e6c1d4a005b914734c2b88ec0e1351e443.

We now give observations with really good signal strength a large weight factor and those with really bad signal strength a really small weight factor below 1.0. The station position is than calculated as the weighted average over the observations, instead of a simple unweighted average.

This will move our estimate of the station position towards its real position, without having to do an analysis over all observations or dealing with single bad outliers.
