### ISSUE TITLE
Wrong mnc in many cases

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/ichnaea#340]
Hello,
i describe the problem here. Maybe it could be a problem from mozstumbler.
In many cases you get a wrong mnc.
If the mnc is 2 there is a wrong mnc 35 
(in a quick way i could detect: right mnc 2 \* 10 + 15 = 35 wrong mnc).

right mnc = wrong mnc
2 = 35
3 = 45
4 = 55
5 = 65
6 = 75
7 = 85
.... = ....

Examples:
Correct mnc is 2, wrong mnc is 35 (2*10+15) 
UMTS,262,35,1607,98764169,367,6.427767,51.36454512,528,25,1,1415996811,1415996930,
UMTS,262,2,1607,98764165,367,6.4221475,51.3645225,48,2,1,1415996811,1415996856,

Correct mnc is 5, wrong mnc is 65 (5*10+15)
UMTS,724,5,31119,40626914,142,,,,1,1,1416010353,,
UMTS,724,65,31119,40631111,142,,,,4,1,1416010354,,

Correct mnc is 7, wrong mnc is 85 (7*10+15)
GSM,262,7,30522,5635,,7.35827552174,51.458758,1244,23,1,1416003070,1416003335,
GSM,262,85,30522,23947,,7.36912988889,51.4595411111,509,9,1,1416003070,1416003135,

Correct mnc is 15, wrong mnc is 165 (15*10+15)
UMTS,208,165,3300,210698333,37,4.269593,43.7506725,22,2,1,1416008910,1416009115,
UMTS,208,15,3300,18886749,65,4.2703835,43.751236,24,2,1,1416008911,1416009115,

208,165 = 1748 matches ["208", "15", "Free Mobile", "Free Mobile"],
240,65 = mnc 5 and 65 exist both as a real mnc but there a many false mnc with 65
262,35 = 9573 matches ["262", "02", "Vodafone D2 GmbH", "Vodafone D2 GmbH"],
262,45 = 5038 matches ["262", "03", "E-Plus Mobilfunk GmbH & Co. KG", "E-Plus Mobilfunk GmbH & Co. KG"],
262,85 = 13515 matches ["262", "07", "Telefonica Germany GmbH & Co. oHG", "Telefonica Germany GmbH & Co. oHG"],
272,45 = 752 matches ["272", "03", "Meteor Mobile Communications Ltd.", "Meteor Mobile Communications Ltd."],
450,95 =  3496 matches ["450", "08", "olleh", "KT"],
724,65 = 876 matches ["724", "05", "CLARO", "CLARO"],

Maybe the false mnc is a problem from mozstumbler or other apps?

**Comment by mar-v-in** [comment]
This is no problem specific to mozstumbler but seems to be a bug in some radio firmwares (not the RIL), including the Nexus 4 (my test device). Interestingly this seems only to happen when using the [getAllCellInfo()](http://developer.android.com/reference/android/telephony/TelephonyManager.html#getAllCellInfo()), not when using [getNetworkOperator()](http://developer.android.com/reference/android/telephony/TelephonyManager.html#getNetworkOperator()).

I also have a theory what might cause the problem here: All problematic MNCs seem to come from countries where the MNC has only 2 digits. To me it sounds likely possible, that the radio firmware developers did not properly test the API for 2 digit MNCs and just assumed that there algorithm would be fine for those as well. This seems perfectly valid in consideration of the 10 * x + 15, which might be caused by taking three digits into calculation and thus reading an additional one (just guessing here: 26207 becomes 0x26207FFF in memory, 07F is used for MNC calculation (100 * 0 + 10 * 7 + 1 * F = 85))
With this is mind, it might be possible to detect and work-around the issue. We can determine if the phone is affected by comparing getAllCellInfo() and getNetworkOperator(). The mcc/mnc of the CellInfo where isRegistered() returns true must match the getNetworkOperator().
However, if the Nexus 4 is the only affected device, the best choice might be to report the bug to Google and hope they'll fix it (they'll not, but we can still hope :pray: ). I guess we need other users to confirm this issue.

I'm currently working on adding cell location support to https://github.com/microg/IchnaeaNlpBackend and I do not plan to add it, if it sends out wrong data to MLS on some devices. Moreover this might be the reason why some people have problems to use geolocation based on offline copies of Mozilla or OpenCellId database.

**Comment by Gitschubser** [comment]
Is there any news? 
The database contains many false cellids with wrong mnc.
