### ISSUE TITLE
geolocate appears to be giving geoip results in when only cell tower data is available

### ISSUE THREAD

**Issue by crankycoder** [mozilla/ichnaea#416]
I'm pretty sure that this is a bug in ichnaea.  Here are screenshots showing my location lookup and the JSON bundle that I uploaded.

![2015-03-10 11 20 41](https://cloud.githubusercontent.com/assets/4829/6578005/f93ff264-c717-11e4-93f0-38de2866646f.png)

![2015-03-10 11 17 57](https://cloud.githubusercontent.com/assets/4829/6577912/6ecc81ec-c717-11e4-94f8-a63371c411b9.png)

**Comment by sshvetsov** [comment]
I was just looking into this. I think the problem is with JSON request object generated in [org.mozilla.mozstumbler.service.stumblerthread.datahandling.StumblerBundle.toMLSGeolocate()](https://github.com/mozilla/MozStumbler/blob/dev/libraries/stumbler/src/main/java/org/mozilla/mozstumbler/service/stumblerthread/datahandling/StumblerBundle.java) and [org.mozilla.mozstumbler.service.stumblerthread.scanners.cellscanner.CellInfo.toJSONObject()](https://github.com/mozilla/MozStumbler/blob/dev/libraries/stumbler/src/main/java/org/mozilla/mozstumbler/service/stumblerthread/scanners/cellscanner/CellInfo.java).

Google Geolocation API request (since [Ichnaea Geolocate API](https://mozilla-ichnaea.readthedocs.org/en/latest/api/index.html#geolocate) points to Goolge as reference) is specified something like this:
```
{
  "radioType": ...,
  "cellTowers": [
    {
      "cellId": ...,
      "locationAreaCode": ...,
      "mobileCountryCode": ...,
      "mobileNetworkCode": ...
    }
  ]
}
```

While MozStumbler generates something like this (note the location of "radioType"):
```
{
  "cellTowers": [
    {
      "cellId": ...,
      "locationAreaCode": ...,
      "mobileCountryCode": ...,
      "mobileNetworkCode": ...,
      "radioType": ...
    }
  ]
}
```

I played around with the "geolocate" API and it seems to work the same as "search" API if "radioType" is in the root of the JSON request. Presence or absence of "radioType" in cellTower object doesn't seem to have an effect on result.

**Comment by crankycoder** [comment]
I'm moving this back to the stumbler client.

**Comment by hannosch** [comment]
The issue is partly on the service side. The geolocate API supports either putting the radioType at the top-level. Or putting a key called "radio" inside each cell record. That is an undocumented workaround that is specific to some versions of Firefox OS.

What we should be accepting, to match the geosubmit API, is a radioType key inside each cell record.
