### ISSUE TITLE
Coverage tile zoom level 0 not available

### ISSUE THREAD

**Issue by cascheberg** [mozilla/ichnaea#452]
The MLS coverage tiles are not available for [zoom level 0](https://d17pt8qph6ncyq.cloudfront.net/tiles/0/0/0.png). I think this is a regression. The image is supposed to be displayed on top of the "Detailed data map" on the [MLS front page](https://location.services.mozilla.com/), but it is broken.

**Comment by hannosch** [comment]
A yeah, I never noticed that since I use a retina display and that uses the `@2x.png`. Looking at the underlying S3 bucket, it turns out there's an old outdated 2x file in the `0/0` folder (about a month old).

The actual files are generated and placed into the top-level folder. Now to figure out how this happened.

**Comment by hannosch** [comment]
Turns out this probably never worked. The frontpage images where always created at `/0.png` + `/0@2x.png`. Why that ever worked when using `/0/0/0.png` is beyond me. I did manually copy the top-level images into the subdirectory, so this should "work" in the meantime until we push out this code fix.

**Comment by hannosch** [comment]
Or wait, I need to read that map.py script again. This isn't as simple as it looks like. I fear this is some / vs. non-/ path joining going wrong.

**Comment by hannosch** [comment]
Looks like I fixed this while refactoring the datamap scripts.
