### ISSUE TITLE
Color old data points different and by age on map

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/ichnaea#466]
The map should style the data points depending on their age so it gets easy to spot where the date is pretty outdated.
Example:
<3 months: green
<2 years: yellow
<5 years: orange
>5 years: red

**Comment by hannosch** [comment]
I've started doing that in ac28df5c80a4a5f51554fa4a37f355470e4cb87a with a slightly different approach. Instead of changing the color scheme, I adjust the number of random points per grid. So grids that have seen more recent updates will have a denser dot cloud. The grid size we use is a ~100x100 meters rectangle. Currently we always put five dots into that grid at random positions, the new approach will vary that number depending on the modification time.

I still have to store the actual modification time for each grid. Currently we only store the time a grid has seen data for the very first time.

Changing the color is difficult, as the dots get merged together at higher zoom levels to provide the "glow effect" (slowly turning white instead of blue).

We are unfortunately limited by the datamaps tool we use to generate this map. There's not much we can change about the process without having to rewrite it all.

**Comment by hannosch** [comment]
The changes went live yesterday. Areas on the map with more recent activity (monthly, up to 6 months ago) are now highlighted more using more points for each map grid (100x100m). Tracking of activity only started yesterday, so this doesn't show what actually happened during the last months but will only work for future updates.
