### ISSUE TITLE
./server css and ./server js fails in docker development

### ISSUE THREAD

**Issue by xiphias256** [mozilla/ichnaea#495]
I've done a clean docker install, following [https://mozilla.github.io/ichnaea/install/devel.html](url)
When I try to run `./server css` it failes with this error:

`.
.
.
Successfully built 3d70e8b98aec
cp /node/bower_components/mozilla-tabzilla/css/tabzilla.css \
	/app/ichnaea/content/static/css/tabzilla.css
cp: cannot create regular file '/app/ichnaea/content/static/css/tabzilla.css': Permission denied
node.make:20: recipe for target 'css' failed
make: *** [css] Error 1
`

When I try to run `./server js` I get this error,
`Step 20 : VOLUME /app
 ---> Using cache
 ---> 3d70e8b98aec
Successfully built 3d70e8b98aec
uglifyjs -c --stats -o /app/ichnaea/content/static/js/bundle-privacy.js \
	/app/ichnaea/content/static/js/privacy.js
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/app/ichnaea/content/static/js/bundle-privacy.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at /node/node_modules/uglify-js/bin/uglifyjs:474:16
    at /node/node_modules/async/lib/async.js:188:33
    at /node/node_modules/uglify-js/bin/uglifyjs:369:9
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
node.make:53: recipe for target 'js' failed
make: *** [js] Error 1`

I'm running this on Ubuntu 16.04 with
`root@tweety:~/git/ichnaea# docker --version
Docker version 1.12.1, build 23cf638
root@tweety:~/git/ichnaea# docker-compose --version
docker-compose version 1.9.0, build 2585387`

**Comment by hannosch** [comment]
This looks like there is a filesystem permission issue.

The css/js commands start a container with the current working directory mounted into it as a volume. Both create files on that volume (images, fonts, css/js files), which should be available outside the container on the host system. Can you check what the filesystem permissions are on the host system under ``ichnaea/content/static/``?

**Comment by xiphias256** [comment]
The files have 664 permission. Directories have 775

**Comment by guigui9213** [comment]
Having the same issue.
When looking closer in the container, it appears that _uid_ and _gid_ of the _/app_ directory is `node:node` instead of `app:app` as mentionned in the Dockerfile.
I had to manually  type in the commands in the `./server` shell script : 
- `cd docker/node; docker build -t mozilla/ichnaea_node .`
- `cd -`
- `docker run -it --rm --volume \backquote pwd \backquote:/app mozilla/ichnaea_node`
- `ls -l`

Then, it appears that _uid_ and _gid_ of _/app_ directory is `node:node`.
A workaround was to log in the container in root and type : 
- `cd /`
- `chown -R app:app /app`

Then, i could run `./server css` and `./server js` commands with no error. But I had the weird consequence that my ichnaea directory on my host had its `uid:gid` changed from my user to `10001:10001`.

I can't find out why all of this happens, I just begin to use Docker so I am not aware of all the way it works.
I can't find why the user and group of _/app_ directory changed from `app:app` in Dockerfile to `node:node` when container is launched.

**Comment by hannosch** [comment]
It looks like this is a general problem with docker and volume permissions (https://github.com/docker/docker/issues/7198).

I can reproduce this problem on a Linux machine, while it works as-is on my macOS (docker for mac) install.

There seem to be a whole lot of workarounds for the permission issue, but I couldn't find any actual short and nice solutions yet.

**Comment by chrisail** [comment]
Hi.
I encountered the same problem on development environnement on Linux 16.04 virtual machine with docker 17.09.0-ce, docker-compose 1.8.0 and Ichnaea 2.2.0.
With some help of a colleague, we made the following changes as a workaround:

- sudo chmod 666 docker/node/npm-shrinkwrap.json
- sudo chmod 666 docker/node/package.json
- sudo chmod 777 -R ichnaea/content/static

Both sudo ./dev css and sudo ./dev js executed fine.

**Comment by gnaazr95** [comment]
The above answer worked for me!

**Comment by willkg** [comment]
A couple of weeks ago, I redid the local dev environment, so the commands are different now. Doing the following both work for me:

```
$ make buildjs
$ make buildcss
```

I think we're all set here. If not, please add a comment with details about what's not working.
