### ISSUE TITLE
OpenCellID closing

### ISSUE THREAD

**Issue by jidanni** [mozilla/ichnaea#497]
https://mozilla.github.io/ichnaea/import_export.html mentions
OpenCellID. But http://wiki.opencellid.org/wiki/Main_Page says that
project might only last through the end of the month. So you need to
revise the page.

**Comment by kolesar-andras** [comment]
I'm an OpenCellID contributor. Source code was not open there, therefore my contribution means a large number of measurements (covering all operators and all radio technologies at the same time), bug reports and suggestions. I'm just getting to know MLS. I think other contributors will also land at MLS soon.

Is it a good idea to upload my all exising measurements to MLS? I think best would be to upload all raw measurements of OpenCellID to MLS. Legal and/or capacity issues? What do you think?

**Comment by hannosch** [comment]
@jidanni Thanks for opening the issue and alerting us. I'll wait with any changes to our website, until it is clear what's going to happen with OpenCellID. At this point there still might be someone else who is willing to take up the project.

**Comment by hannosch** [comment]
@kolesar-andras Welcome :)

In regards to uploading measurements/observations:
1. We appreciate getting any additional data. We do purge and ignore data that is too old. We currently treat anything older than a year as too old and unreliable, as the real world might have changed in the meantime, so old data at some point becomes untrustworthy.
2. There is no legal issue if you upload data you have gathered yourself, as you still retain the rights to that data.
3. Capacity wise it shouldn't be a problem, but you could be nice about it and upload data in chunks of 1mb spread out over an hour or more.

We cannot take in all of OpenCellIDs data and mix this into our own data. OpenCellID publishes both the raw data as well as the aggregate dataset under a CC-BY-SA 3.0 / Odbl 1.0 license, which is incompatible with our license scheme. Our own aggregate cell data is published under the more permissive CC-0 license without any share-alike clauses.

**Comment by kolesar-andras** [comment]
Thank you for welcome.

1. I collect data from year 2008. First six years only by a vehicle tracking equipment, gsm technology at one operator. However there are places where no one collected measurements since than. I have checked that cell ids don't change in time. There are new stations, existing stations are extended with new cells and new technologies, some are discontinued because building constructions but 95% of the cells measured in the last ten years still work at the same place. From 2014 I use more and more phones at the same time, now I can cover all operators and all radio access technologies at the same time. I plan my trips to cover as much from the road network as possible to get cells from every directions of base stations. I'm unable to drive through all the roads in one year in my country. There are places where I have traveled last year and some others where the I was only in 2015. Therefore if you filter uploaded data out that is older than a year you miss cells. I have lots of measurements from places where no one have measured those cells.

2. Fortunately I have exported all my measurements to local files before uploading to OpenCellID.

3. I will use an upload script that respects the upload rate you have specified.

I think we could ask Markus at OpenCellID to release raw data under CC-0 license.

**Comment by jidanni** [comment]
I sure hope you don't mean you even throw out data within the system
that reaches one year old too.

And anyway don't assume the whole world changes at the same rate.
Or that people will hike that often to many places.

And I hope all this throwing out is documented.

Also if you can't use OpenCellID data, then you should not mention
OpenCellID on the MLS website.

By the way the OpenCellID API is broken when you try to copy your data
out. So indeed having copied it before uploading was smart.

**Comment by kolesar-andras** [comment]
I have asked Markus about releasing OpenCellID data under CC-0 licence. He replied: "this is a good idea".

**Comment by takiainen** [comment]
If I've understood correctly, the mozilla database is not fully open  - i.e. compared with radiocells.org, where all the data is freely available for anyone. After hearing this sad news of OCID closure, I'm glad I've always been collecting for both of them at the same time (radiocells and ocid).  Since as we know now, these projects can die - especially if there's only a handful of people behind it (or just one).

**Comment by gopi-ar** [comment]
Just a note, OCID isn't closing down. My company Unwired Labs has taken over maintainership of this project and on the immediate roadmap are plans to revive it's dying community and data quality.

We're in the middle of transferring data / code / etc to our servers from Enaikoon's and should publish the roadmap on the wiki shortly after that. In the meantime, we're reachable on hello@opencellid.org

Cheers,
Gopi

**Comment by hannosch** [comment]
@gopi-ar Awesome news! Thanks a lot for taking over OCID.

Looks like there's nothing to do on our end at the moment. We'll wait and see what your plans and roadmap are for OCID and how we can help or collaborate going forward.
