### ISSUE TITLE
Geolocate API equivalent when using Development Version of service

### ISSUE THREAD

**Issue by gnaazr95** [mozilla/ichnaea#512]
When calling the Geolocate API generally all one has to do is: https://location.services.mozilla.com/v1/geolocate?key=test and then POST a JSON body such as: 
```
{
    "cellTowers": [{
        "radioType": "wcdma",
        "mobileCountryCode": 208,
        "mobileNetworkCode": 1,
        "locationAreaCode": 2,
        "cellId": 1234567,
        "signalStrength": -60
    }]
}
```

How can I do something similar when I have my own Development Version of the service? I set up the service and am able to see expected output when running curl -i http://localhost:8000/__heartbeat__ 
& curl -H "X-Forwarded-For: 81.2.69.192" \ http://localhost:8000/v1/geolocate?key=test.

How would I set up/run a request to get data using the development version of the service similar to how it works with the Geolocate API? I couldn't find much about it on the documentation or other online sources.

Thanks for reading!

**Comment by gnaazr95** [comment]
After looking into it a little, it seems like the database that Ichnaea utilizes in its own service is IP-based (meaning I need to have the IP Address of the cell to get the latitude and longitude). I'm assuming that there is no option for another database that I could use with Ichnaea that would require me to input data about the cell (cell ID, LAC, MNC, MCC, etc.) and would give me the latitude and longitude (I'm only given this information in my application, not the IP Address).

**Comment by willkg** [comment]
I think there are two underlying needs here:

1. documentation on how to test out a local development environment
2. sample data

The second is covered by issue #503 .

We should document how to test out a local development environment. Maybe this overlaps with #827 especially if that system test has manual parts.

I'm going to toss this in the "new infra" milestone, because we want to work on both of those things for that milestone.
