### ISSUE TITLE
Maxmind database handles need to be refreshed regularly

### ISSUE THREAD

**Issue by crankycoder** [mozilla/ichnaea#521]
We need a mechanism to enable the maxmind database handles to be refreshed when operations updates the database.  

cc/ @ckolos

**Comment by willkg** [comment]
We talked about this on IRC a little.

I just landed gunicorn configuration changes that add max-requests and max-requests-jitter so the webapp workers will recycle periodically.

@jwhitlock said he'd feel better if the maxmind db things were versioned with everything else, so then a deploy would push out the new version.

@ckolos said "ick" because that means we need to do weekly deploys. I posited that it might be nice anyhow because it lets us roll back more easily.

@ckolos said that the maxmind db things are installed via an RPM on the host and that he currently HUPs the process.

I think that summarizes everything that was said.

**Comment by jwhitlock** [comment]
It's unclear to me if there is additional work to do here. It seems that the process can be fully automated, and, if it isn't, then the manual bits are there by the discretion of operations.

An automated process would be:

* Run a nightly or weekly cronjob to install the new maxmind db via an RPM
* Wait 10 minutes
* Check https://location.services.mozilla.com/__heartbeat__ to see if the new database was loaded.

@ckolos, is there additional work to do here?

**Comment by jwhitlock** [comment]
@ckolos says this is no longer a concern with the 2020 infrastructure.
