### ISSUE TITLE
system test

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#827]
Ichnaea has a set of tests in `tests/` subdirectories across the code base. I think most of these are unit tests and there are probably some integration tests in there. That's cool.

What I would like is to have a system test that you can give an auth token and a url (local dev environment, stage, prod) or something along those lines and have it test the important functional requirements of the entire system.

This issue covers that.

**Comment by hannosch** [comment]
For a systems test, you could try to automate the steps mentioned in https://mozilla.github.io/ichnaea/install/debug.html as a start.

I‘ve been known to take a slice of production data and run it through my local dev pipeline, but that isn‘t an automatable approach.

**Comment by willkg** [comment]
I started writing up some scripts for this. It's a little tricky since processing incoming reports takes an unknown amount of time, so it's hard to do a geolocate query on data submitted with a new geosubmit report.

The scripts I had were good enough to test stage, so I'm bumping this out of the new infra milestone.

**Comment by jwhitlock** [comment]
I've also created some scripts that setup arguments for ``curl``, calling it like:

```
curl -v https://location.stage.mozaws.net/v1/geolocate?key=the_test_key --data @test-locate.json
```

They were also good enough for my tests of new servers, but I didn't want to submit them to the repo because 1) I didn't want to commit working API keys, or 2) test data. I may formalize them as part of developing for other issues, like a fast processing mode for local development (#1409) or creating fake sample data (#503).
