### ISSUE TITLE
expire unhelpful data

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#845]
We currently have a monotonically increasing database that's pretty large and that's not sustainable. We need to figure out either a policy for how long data sticks around for or some algorithm for expiring "least helpful data".

There are a couple of related comments in the issue tracker.

This talks about expiring data:

* https://github.com/mozilla/ichnaea/issues/509#issuecomment-327161982

These talk about expiring known bad data:

* https://github.com/mozilla/ichnaea/issues/489
* https://github.com/mozilla/ichnaea/issues/510
* https://github.com/mozilla/ichnaea/issues/486

It'd be great if we could figure out some algorithm that we could encode in a task that runs weekly and removes data from the db.

**Comment by willkg** [comment]
Some data points:

```
MySQL [location]> select count(*) from wifi_shard_0 where last_seen is NULL;
+----------+
| count(*) |
+----------+
| 16394938 |
+----------+
1 row in set (16 min 47.15 sec)
MySQL [location]> select count(*) from wifi_shard_0;
+-----------+
| count(*)  |
+-----------+
| 115824396 |
+-----------+
1 row in set (2 min 43.66 sec)
```

Can we remove these? Will it noticeably affect existing geolookup queries?

(Caveat: I'm a developer, but I'm new to geo lookup, so this none of this is obvious to me. Using small words and or pointing to code/docs helps.)

**Comment by hannosch** [comment]
IIRC the query APIs all have thresholds built-in, so way too old data isn’t used anyways. Or rather at some point old data gets such a low confidence score, a location based on GeoIP is preferred. So deleting those networks shouldn’t impact the service quality in any major way.

As a first step, I’d focus on wifi networks, as those make up the bulk of the data. For those I’d look at all wifi networks, which haven’t been modified in the past two years and delete those. Since the modified column is indexed, those queries should be reasonably quick. I think deletions worked quite ok when done in batches of no more than 10000 rows at a time. Otherwise transactions took too long and the MySQL db replication ran into problems.

**Comment by willkg** [comment]
We're not switching cloud providers, so I think we don't get a ton of value out of doing this right now. I'm going to bump this out of the "new infra" milestone.

**Comment by jwhitlock** [comment]
This rhymes with [bug 1602958](https://bugzilla.mozilla.org/show_bug.cgi?id=1602958), "determine data staleness", filed on 2019-12-10. There is some original research, including graphs and tables, in that bug.
