### ISSUE TITLE
figure out how to set up mapbox and document it

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#848]
The local dev environment needs mapbox token.

This issue covers figuring out how to set that up, adding whatever code bits are needed, and documenting the process in the local dev environment docs.

**Comment by hannosch** [comment]
Mapbox has a free tier, so you should be able to get a token that way. Otherwise you can figure out who is in charge of the Mapbox account for Mozilla and let them get you a new token for local development and share that. The map tiles url you need is for the output of the datamap script. This used to be a volume mount from the docker container at “something/static/something other I can’t remember”.
