### ISSUE TITLE
load test 

### ISSUE THREAD

**Issue by willkg** [mozilla/ichnaea#851]
We're in the process of moving MLS to a new infrastructure. We need to load test MLS on the new infrastructure.

This issue covers figuring out what that load test should look like and writing the required bits.

**Comment by hannosch** [comment]
One trick you can employ, is to configure the production instance to send all its data to an additional upstream service (i.e. your new environment). You can do that in the `export_config` table.

This doesn't replicate the locate traffic, but it is a good stress test for the async workers. Otherwise there's a S3 bucket with all the prod data in it and you could run that against a new instance. As long as the data is kept on trustworthy machines, you shouldn't have a privacy problem.

**Comment by willkg** [comment]
We did exactly that: added a geosubmit export to prod to send data to stage. That's good enough load test to tell us that things aren't egregiously different between the old stuff and the new stuff.
