### ISSUE TITLE
create db migrate entrypoint for admin server

### ISSUE THREAD

**Issue by ckolos** [mozilla/ichnaea#979]
To facilitate CI/CD in stage, it would be really helpful to have a entrypoint to the container that will call alembic to perform the migration as part of the jenkins pipeline for deployment

**Comment by willkg** [comment]
You can do this now:

```
docker run DOCKEROPTS IMAGE shell SHELLCOMMANDS
```

For example, this will run `alembic current`:

```
docker run DOCKEROPTS IMAGE shell alembic current
```

Does that help/work?

**Comment by ckolos** [comment]
Yes, I think it will. I'll start testing this on the next opportunity to do a DB migration.

**Comment by willkg** [comment]
Now that I'm thinking about this, I thought we decided to not do database migrations automatically and instead run them manually after deploys and that'd be ok because:

1. we don't expect to do them often--they will be unusual
2. we plan to do multi-step changes with database migrations so there's no race condition between pushing code and running the database migration
3. the database is huge, so database migrations may take a long time to run and may have special needs

My vote is we hold off on automatically running migrations during deploys.

**Comment by willkg** [comment]
Oops--scratch everything I said in that last comment. According to https://bugzilla.mozilla.org/show_bug.cgi?id=1589157#c1 we did decide to automatically do migrations during deploys.

Sorry for the confusion!

**Comment by ckolos** [comment]
This would only be done in stage/-dev. No worries though.

**Comment by willkg** [comment]
We're good here. Marking as FIXED.
